### ISSUE TITLE
Error using untouched code

### ISSUE THREAD

**Issue by jay-jlm** [howdyai/botkit-starter-facebook#1]
Here's an error I get when running this example code, after I try to talk to it from facebook messenger

```
info: ERROR IN RECEIVE MIDDLEWARE:  TypeError: Cannot convert undefined or null to object
    at addTeamInfo (/home/joao/node-projects/make-me-fat-bot/node_modules/dashbot/src/dashbot.js:169:12)
    at Ware.DashBotSlack.that.receive (/home/joao/node-projects/make-me-fat-bot/node_modules/dashbot/src/dashbot.js:230:25)
    at Ware.<anonymous> (/home/joao/node-projects/make-me-fat-bot/node_modules/wrap-fn/index.js:45:19)
    at next (/home/joao/node-projects/make-me-fat-bot/node_modules/ware/lib/index.js:85:20)
    at Ware.run (/home/joao/node-projects/make-me-fat-bot/node_modules/ware/lib/index.js:88:3)
    at Object.Botkit.botkit.receiveMessage (/home/joao/node-projects/make-me-fat-bot/node_modules/botkit/lib/CoreBot.js:1067:35)
    at Object.Facebookbot.facebook_botkit.handleWebhookPayload (/home/joao/node-projects/make-me-fat-bot/node_modules/botkit/lib/Facebook.js:310:45)
    at /home/joao/node-projects/make-me-fat-bot/components/routes/incoming_webhooks.js:18:20
    at Layer.handle [as handle_request] (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/layer.js:95:5)
    at /home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/index.js:330:12)
    at next (/home/joao/node-projects/make-me-fat-bot/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/home/joao/node-projects/make-me-fat-bot/node_modules/serve-static/index.js:75:16)
```

**Comment by sinned** [comment]
It's most likely line 6 in this code:
https://github.com/howdyai/botkit-starter-facebook/blob/master/components/plugin_dashbot.js

It's asking for the .slack version of the Dashbot API, when this should be using the .facebook one (since it's a Facebook bot).

I'll fix and submit a pull request.

**Comment by sinned** [comment]
I fixed the issue and submitted a pull request:
https://github.com/howdyai/botkit-starter-facebook/pull/2

**Comment by benbrown** [comment]
thanks @sinned!!

**Comment by jay-at-avido** [comment]
It looks like error was in the dashbot integration and according to a commiter has already been fixed on their part:
https://github.com/actionably/dashbot/issues/11
